### ISSUE TITLE
publisher message

### ISSUE THREAD

**Issue by jfriend08** [brooklyn-omniheurists/evasion#24]
left is server, middle is ruby hunter.rb, right is my code for prey

At some point, hunter just stop updating, I think it's due to not receiving publisher's message?
While prey can still receive message with no problem.

![screen shot 2015-11-02 at 8 45 16 am](https://cloud.githubusercontent.com/assets/5174913/10883244/9e056938-813e-11e5-96ad-b400070b484c.png)

**Comment by brooklyn-omniheurists** [comment]
@jfriend08 The ruby random only prints out the publishers message, but doesn't do anything with it. It indiscriminately sends messages to the server regardless of what the publisher says. I'll try to see what's causing it to stop printing, it doesn't look like the connection was dropped.

**Comment by brooklyn-omniheurists** [comment]
@jfriend08 yooooooooo i think i know what it is.

The connection gets closed because there isn't a two way stream, so i guess whatever library we're using kills it to save memory.

A simple way to keep it alive is:

``` ruby
loop do
  dr = do_something
  sleep 0.5
  publisherSocket.send "stay alive"
  hunterSocket.send dr.to_json
end
```

Again, the ruby was just for debugging purposes, so this was a low prio. Hope it helps, keep writing great code.

**Comment by jfriend08** [comment]
yea, thanks! 
Looks good
