### ISSUE TITLE
How should we set up browser ui?

### ISSUE THREAD

**Issue by CodeOsiris** [brooklyn-omniheurists/evasion#34]
The readme file is not really saying much about how we should do wrt this project. 
So I have installed angular-seed, and after npm start I am able to open http://localhost:8000/app/index.html, but it's nothing more than a Hello world page, do we need to move our files into somewhere?

**Comment by brooklyn-omniheurists** [comment]
@19thhell Sorry, that `README.md` is the general readme for angular, which is what we used to build the UI.

In our readme, we've [documented the truth](https://github.com/brooklyn-omniheurists/evasion#high-level-architecture). Somewhere there it shows the actual url one should go to.

 I think the documentation could be a bit better, but here's the gist of it, i'll fix it later:

``` bash
$ node server.js
```

or

``` bash
$ nodejs server.js
```

After the server starts, no need to do any `npm start`, just go to the following url:
[`http://localhost:8080/evasion-ui/app/`](http://localhost:8080/evasion-ui/app/)

`http://localhost:8000/app/index.html` shows a hello world page because it is a hello world page, if it helps we can remove any files that aren't helpful in the project to save confusion.

Hope that helps.

**Comment by CodeOsiris** [comment]
I followed your instruction and now it says "Cannot GET /evasion-ui/app/"

**Comment by brooklyn-omniheurists** [comment]
I'm sorry I cannot recreate, but a couple of things to note.
1. The good news is that the server is working. Otherwise you wouldn't get that error.
2. Verify you have the latest version of [this](https://github.com/brooklyn-omniheurists/evasion/blob/master/evasion-ui/app/index.html) file in the correct location (the same dir structure as this repo)

The reason I ask for # 2 up there is because I see you were reading [this readme](https://github.com/brooklyn-omniheurists/evasion/tree/master/evasion-ui) which asks for you to run a `git` command. It may be that you may have inadvertently downloaded their repo as a submodule, so running `git status` will show you that nothing has changed in that directory, but in reality you've added a submodule.

Again, I have no idea if that's the case. I only bring that up because it happened with one of our engineers, so I know it happens to the best of us. If I could see what you were working with, I'd be able to  offer more help.
