### ISSUE TITLE
Reflection is different from website

### ISSUE THREAD

**Issue by KshitizSethia** [brooklyn-omniheurists/evasion#4]
The reflection you showed in readme is different from the one on the website:

Technical note about bouncing: The walls are one unit thick, and centered at integer coordinate. For any integer coordinate that is within a wall, the wall extends (at least) .5 units above, below, left, and right of it. So, if there is a wall from (10,200) to (300,200) and a player begins at (100, 199) moving +1 in x and +1 in y, it will reflect to (101, 199) at the end of the time step. Neither player will bounce off the narrow side of a wall (except the special case described below). So, a player who begins at (9, 200) moving +1 in x and +1 in y, it will not reflect and will simply move to (10, 201), still moving +1 in x and +1 in y. A player who hits a corner of a wall will bounce off as if they hit the middle of the wall. So, a player who begins at (9, 199) moving +1 in x and +1 in y will reflect and end up at (10, 199) moving +1 in x and -1 in y.

So, which one do we follow?

**Comment by mayanks43** [comment]
Why do you think this is different? Seems ok to me. Anything specific?

**Comment by brooklyn-omniheurists** [comment]
I think it's the same as well. In any case, please follow the one specified in the architecture. For example, we will not support diagonal walls, something professor agreed made sense.

**Comment by KshitizSethia** [comment]
In the first example. If the hunter is at 100,199 and bounces on 101,200, then it should end up at 102,200 according to conventional reflection rules and diagrams here.

According to the website, it bounces from 101,200 and goes "up" to 101,199.

**Comment by brooklyn-omniheurists** [comment]
@kshitizSethia I see what you're saying, let me clarify!

In the diagrams on the readme, there are two things going on, the hunter is "bouncing" by moving position and also changing direction. It may seem like it's "conventional" bouncing but it's actually not!

Look at the diagram for vertical bounce. The hunter collides on the wall going `SE`. The result is it moves `S` and it's direction is reflected along the `Y` axis.

That very same thing happens in horizontal walls, although in our diagram, it may look like otherwise. What's happening is that the hunter is bouncing off the horizontal wall, but first it moves 1 unit in the X direction, and then it's `Y` gets reflected.

The diagrams show the hunters position, and it's direction on one step!

Please let me know if that explains it!
